version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: web3_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: rewtqasw3253
    ports:
      - "5430:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d web3_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  activemq:
    image: apache/activemq:5.19.6
    container_name: activemq
    restart: unless-stopped
    ports:
      - "61616:61616"
      - "8161:8161"
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
    healthcheck:
      test: [ "CMD", "bash", "-c", "echo > /dev/tcp/localhost/61616" ]
      interval: 10s
      timeout: 5s
      retries: 5

  lab:
    build:
      context: ./lab
      dockerfile: Dockerfile
    container_name: lab
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "9990:9990"
    depends_on:
      postgres:
        condition: service_healthy
      activemq:
        condition: service_started
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: web3_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: rewtqasw3253

      ACTIVEMQ_BROKER_URL: tcp://activemq:61616
      ACTIVEMQ_USER: admin
      ACTIVEMQ_PASSWORD: admin

  payment-service:
    build:
      context: ./paymentService
      dockerfile: Dockerfile
    container_name: payment-service
    restart: unless-stopped
    ports:
      - "8085:8085"
    depends_on:
      activemq:
        condition: service_healthy
    environment:
      ACTIVEMQ_BROKER_URL: tcp://activemq:61616
      ACTIVEMQ_USER: admin
      ACTIVEMQ_PASSWORD: admin

volumes:
  postgres_data:
