spring.application.name=BLPS-CRUD

spring.datasource.url=jdbc:postgresql://localhost:5432/web3_db
spring.datasource.username=user
spring.datasource.password=rewtqasw3253
spring.jpa.hibernate.ddl-auto=update
