spring.application.name=BLPS-CRUD

spring.datasource.url=jdbc:postgresql://localhost:5432/web3_db
spring.datasource.username=user
spring.datasource.password=rewtqasw3253
spring.jpa.hibernate.ddl-auto=update

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.tags-sorter=alpha
springdoc.default-produces-media-type=application/json

security.users-file=./security-users.xml
