spring.application.name=BLPS-CRUD

spring.datasource.url=jdbc:postgresql://localhost:5432/studs
spring.datasource.username=s408344
spring.datasource.password=9Rj196RrKJTGHYkG
spring.jpa.hibernate.ddl-auto=update
