spring.application.name=BLPS-CRUD

server.port=8080

#spring.datasource.url=jdbc:postgresql://localhost:5430/web3_db
#spring.datasource.username=user
#spring.datasource.password=rewtqasw3253
spring.datasource.jndi-name=java:jboss/datasources/PostgreDS
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.transaction.coordinator_class=jta
spring.jpa.properties.hibernate.transaction.jta.platform=org.hibernate.engine.transaction.jta.platform.internal.JBossAppServerJtaPlatform
spring.jpa.properties.hibernate.connection.provider_disables_autocommit=true

spring.jta.enabled=true
spring.transaction.default-timeout=30

payment.provider-url=http://localhost:8085/pay

spring.activemq.broker-url=${ACTIVEMQ_BROKER_URL:tcp://localhost:61616}
spring.activemq.user=${ACTIVEMQ_USER:admin}
spring.activemq.password=${ACTIVEMQ_PASSWORD:admin}
spring.jms.listener.session.acknowledge-mode=client

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.tags-sorter=alpha
springdoc.default-produces-media-type=application/json

security.users-file=./security-users.xml

logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG
logging.level.org.springframework.orm.jpa=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.ru.gigasigma.blpscrud=DEBUG
logging.level.org.springframework.jms=DEBUG
logging.level.org.apache.activemq=DEBUG
logging.level.javax.jms=DEBUG
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-exception=true
